suppressMessages(library(foreach))
suppressMessages(library(doParallel))
suppressMessages(library(parallel))
suppressMessages(library(doMC))
suppressMessages(library(stringr))
suppressMessages(library(hgu133plus2.db))
suppressMessages(library(hgu133a.db))
suppressMessages(library(affy))
suppressMessages(library(simpleaffy))
suppressMessages(library(affyPLM))
suppressMessages(library(affycoretools))
suppressMessages(library(affyQCReport))
suppressMessages(library(annaffy))
suppressMessages(library(limma))
#suppressMessages(source("Src/GSEA.1.0.R", verbose = TRUE, max.deparse.length = 9999))