back_methods = c("GCRMA", "LESN2")
normalize_methods = c("quantile", "scaling")
summary_methods = c("median.polish", "tukey.biweight", "log.median", "rlm")
p_change = c(0.05, 0.01)
lfc_change = c(0.5, 1, 1.5)
local_statistics = c("Signal2Noise", "tTest", "log2_Ratio_of_Classes")
permutation_type = c("phenotype", "gene_set")